-- ============================================================
-- ENABLE UUID SUPPORT
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- 1. WORKSPACE DATABASES (AGENT REGISTRATION)
-- ============================================================
-- Represents a logical database connected via a VPC agent
-- NO database credentials stored here
-- ============================================================

CREATE TABLE workspace_databases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL,

  name TEXT NOT NULL,                      -- e.g. "Production DB"
  db_type TEXT NOT NULL DEFAULT 'postgres',

  agent_endpoint TEXT NOT NULL,            -- http://10.0.1.12:3001
  agent_token TEXT NOT NULL,               -- shared secret

  status TEXT DEFAULT 'active',            -- active | disabled
  last_tested_at TIMESTAMP,

  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- 2. DATABASE SCHEMA SNAPSHOT
-- ============================================================
-- Stored schema metadata fetched from VPC agent
-- Used by AI to generate SQL (NO DATA ROWS)
-- ============================================================

CREATE TABLE db_schema_snapshot (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  workspace_id UUID NOT NULL,
  database_id UUID NOT NULL
    REFERENCES workspace_databases(id)
    ON DELETE CASCADE,

  schema_version INT DEFAULT 1,
  schema_hash TEXT NOT NULL,
  snapshot JSONB NOT NULL,

  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),

  UNIQUE (database_id)
);

CREATE INDEX idx_schema_snapshot_json
  ON db_schema_snapshot
  USING GIN (snapshot);

-- ============================================================
-- 3. USER QUERIES (CHAT INTENT & CONTEXT)
-- ============================================================
-- Each user question (supports follow-ups)
-- ============================================================

CREATE TABLE db_queries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  workspace_id UUID NOT NULL,
  database_id UUID NOT NULL
    REFERENCES workspace_databases(id),

  user_id UUID NOT NULL,

  natural_language TEXT NOT NULL,
  intent TEXT NOT NULL,        -- new_query | followup | visualization | schema | blocked
  parent_query_id UUID
    REFERENCES db_queries(id),

  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_db_queries_workspace
  ON db_queries(workspace_id);

CREATE INDEX idx_db_queries_parent
  ON db_queries(parent_query_id);

-- ============================================================
-- 4. SQL GENERATIONS (AI OUTPUT)
-- ============================================================
-- SQL generated by AI (versioned)
-- ============================================================

CREATE TABLE db_sql_generations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  query_id UUID NOT NULL
    REFERENCES db_queries(id)
    ON DELETE CASCADE,

  generated_sql TEXT NOT NULL,
  generation_version INT DEFAULT 1,

  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_sql_generations_query
  ON db_sql_generations(query_id);

-- ============================================================
-- 5. HUMAN APPROVALS (GUARDRAIL)
-- ============================================================
-- Human-in-the-loop before execution
-- ============================================================

CREATE TABLE db_query_approvals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  sql_generation_id UUID NOT NULL
    REFERENCES db_sql_generations(id)
    ON DELETE CASCADE,

  status TEXT NOT NULL,        -- approved | rejected | edited
  approved_by UUID,
  comments TEXT,
  approved_at TIMESTAMP
);

CREATE INDEX idx_query_approvals_sql
  ON db_query_approvals(sql_generation_id);

-- ============================================================
-- 6. QUERY EXECUTIONS (AUDIT)
-- ============================================================
-- Executed by VPC agent ONLY
-- ============================================================

CREATE TABLE db_query_executions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  sql_generation_id UUID NOT NULL
    REFERENCES db_sql_generations(id),

  executed_sql TEXT NOT NULL,
  execution_time_ms INT,
  row_count INT,

  executed_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_query_exec_sql
  ON db_query_executions(sql_generation_id);

-- ============================================================
-- 7. QUERY RESULTS (DATA SNAPSHOT)
-- ============================================================
-- Limited result rows returned by agent
-- ============================================================

CREATE TABLE db_query_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  query_execution_id UUID NOT NULL
    REFERENCES db_query_executions(id)
    ON DELETE CASCADE,

  result_snapshot JSONB NOT NULL,
  summary_stats JSONB,

  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_query_results_exec
  ON db_query_results(query_execution_id);

-- ============================================================
-- 8. GENERATED RESPONSES (AI EXPLANATION)
-- ============================================================
-- Natural language explanation of results
-- ============================================================

CREATE TABLE db_query_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  query_result_id UUID NOT NULL
    REFERENCES db_query_results(id)
    ON DELETE CASCADE,

  response_text TEXT NOT NULL,
  generated_by TEXT DEFAULT 'ai',   -- ai | human | edited

  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_query_responses_result
  ON db_query_responses(query_result_id);

-- ============================================================
-- 9. CHART DEFINITIONS
-- ============================================================
-- Saved chart configuration (no raw rendering logic)
-- ============================================================

CREATE TABLE db_charts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  query_result_id UUID NOT NULL
    REFERENCES db_query_results(id)
    ON DELETE CASCADE,

  chart_type TEXT NOT NULL,         -- line | bar | area | pie | table
  chart_config JSONB NOT NULL,

  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_charts_result
  ON db_charts(query_result_id);

-- ============================================================
-- 10. SAVED ANALYSES (REPORTS)
-- ============================================================
-- User-saved insights for reuse & sharing
-- ============================================================

CREATE TABLE db_saved_analyses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  workspace_id UUID NOT NULL,
  user_id UUID NOT NULL,

  name TEXT NOT NULL,
  description TEXT,

  query_id UUID
    REFERENCES db_queries(id),
  query_result_id UUID
    REFERENCES db_query_results(id),

  is_pinned BOOLEAN DEFAULT false,

  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_saved_analyses_workspace
  ON db_saved_analyses(workspace_id);

CREATE INDEX idx_saved_analyses_user
  ON db_saved_analyses(user_id);

-- ============================================================
-- UPDATED_AT TRIGGER (SHARED)
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_workspace_databases_updated_at
BEFORE UPDATE ON workspace_databases
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_schema_snapshot_updated_at
BEFORE UPDATE ON db_schema_snapshot
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_saved_analyses_updated_at
BEFORE UPDATE ON db_saved_analyses
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- END OF MIGRATION
-- ============================================================
